language: php
php:
  - '5.5'
  - '5.6'
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm
 
before_script:
    - composer self-update
    
script:
    - phpunit
 
notifications:
    email: false
